name: Validate API

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      working-directory: ./api-test-harness
      run: |
        # Install dependencies with or without package-lock.json
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
        # Install additional required packages
        npm install @redocly/cli mocha mochawesome --save-dev
        npm list
      
    - name: Run OpenAPI validation
      working-directory: .
      run: npx @redocly/cli lint "API Docs/openapi.yaml"
      
    - name: Run API validation tests
      working-directory: ./api-test-harness
      env:
        NODE_ENV: test
      run: |
        mkdir -p test-results
        npx mocha test/validation/*.test.js --reporter mochawesome --reporter-options reportDir=test-results,reportFilename=test-results
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          api-test-harness/test-results/
        retention-days: 7
